keys:
  # hosts
  - &hosts:
    - &winterfell age1vm8s3yrd5vhc3uvy8mzw9e5r3r0yj5q2ck37wt52c05un6spr9tqvls206

creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *winterfell
